'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={folder:'M3 6h6l2 3h10v11H3Z',arrow:'M4 12h16m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',search:'M20 20l-5-5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',warning:'m12 3 10 18H2Zm0 6v5m0 3v.1',drive:'M4 4h16v16H4Zm0 11h16m-4 2v.1m-3-.1v.1'};
const icon=(name,extra='')=>`<svg class="icon ${extra}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.folder}"/></svg>`;
const names=['Projects','Destination','Data & temp','Review'];
const state={page:0,visited:0,projects:[],storage:'',project_destination:'',destinations:{},items:[],selected:new Set(),tools_temp:'',claude_temp:'',verify_contents:false,apps_closed:false,session:null,view:'setup',search:null,searchCategory:'project',snapshot:null,ready:false,pending:false};
let api=null,polling=false;
function theme(value){let dark=value==='dark'||value==='system'&&matchMedia('(prefers-color-scheme:dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';$('#theme').value=value;try{localStorage.setItem('appearance',value)}catch{}}
let initialTheme='system';try{initialTheme=localStorage.getItem('appearance')||'system'}catch{}theme(initialTheme);
$('#theme').addEventListener('change',e=>theme(e.target.value));matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{if($('#theme').value==='system')theme('system')});
function size(n){let u=0;while(n>=1024&&u<4){n/=1024;u++}return new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(n)+' '+['B','KB','MB','GB','TB'][u]}
function leaf(p){return p.replace(/[\\/]+$/,'').split(/[\\/]/).pop()||p}function join(p,...parts){return p.replace(/[\\/]+$/,'')+(p.includes('\\')?'\\':'/')+parts.join(p.includes('\\')?'\\':'/')}
function error(message=''){$('#error').textContent=message;$('#error').hidden=!message}
async function call(method,...args){if(!api)throw Error('Desktop connection is not ready');return api[method](...args)}
async function act(operation){if(state.pending)return;state.pending=true;error();try{await operation()}catch(e){error(e.message||String(e))}finally{state.pending=false;updateButtons()}}
function button(text,action,cls='',disabled=false){return `<button data-action="${action}" class="${cls}" ${disabled?'disabled':''}>${text}</button>`}
function heading(title,copy){return `<h1 tabindex="-1">${title}</h1><p class="intro">${copy}</p>`}
function field(id,label,value,help=''){return `<div class="field"><label for="${id}">${label}</label><div class="field-control"><input type="text" id="${id}" value="${esc(value)}" autocomplete="off" spellcheck="false">${button('Browse…','pick-'+id)}</div>${help?`<p class="small">${help}</p>`:''}</div>`}
function row(path,index,kind='project'){return `<div class="row">${icon('folder','folder')}<div class="row-main"><div class="row-title">${esc(leaf(path))}</div><div class="path">${esc(path)}</div></div><button class="icon-button quiet" data-action="remove-${kind}" data-index="${index}" aria-label="Remove ${esc(leaf(path))}">${icon('close')}</button></div>`}
function check(id,label,detail='',checked=false){return `<label class="check-row"><input type="checkbox" id="${id}" ${checked?'checked':''}><span><strong>${label}</strong>${detail?`<span class="small">${detail}</span>`:''}</span></label>`}
function render(focus='h1'){error();$('#steps').innerHTML=names.map((n,i)=>`<button class="step ${i<state.page?'done':''}" data-step="${i}" ${state.view!=='setup'||i>state.visited?'disabled':''} ${state.view==='setup'&&i===state.page?'aria-current="step"':''}><span class="number">${i<state.page?icon('check'):i+1}</span>${n}</button>`).join('');
 let content='',actions='';
 if(state.view==='setup'){
  if(state.page===0){content=heading('Choose projects.','Choose a project folder, or the parent folder containing your projects.')+`<div class="list">${state.projects.length?state.projects.map((p,i)=>row(p,i)).join(''):`<div class="empty">${button(icon('folder')+'Choose a folder','add-project','primary')}</div>`}</div><div class="toolbar">${state.projects.length?button(icon('plus')+'Add folder','add-project'):''}${button(icon('search')+'Find existing projects','find-projects','quiet')}${button('Scan a folder…','scan-projects','quiet')}</div><div class="notice">${icon('warning')}<div><strong>Make a separate manual backup before starting.</strong>Use this tool at your own risk. File corruption or a target-drive failure can cause data loss.</div></div>`;actions=`<div>${button('Open saved setup','restore','quiet')}${button('Resume last','recent','quiet')}</div><div class="right">${button('Continue '+icon('arrow'),'next','primary',!state.projects.length)}</div>`}
  if(state.page===1){content=heading('Choose destination.','Choose the folders for projects and tool storage.')+field('storage','Storage folder',state.storage)+`<div id="drives" class="drive-list"></div>`+field('project_destination','Projects folder',state.project_destination,'Also used as the suggested location for new projects.')+`<div class="section-header"><h2>Project destinations</h2><span class="small" id="space"></span></div><div class="list">${state.projects.map((p,i)=>`<div class="row"><div class="row-main"><div class="row-title">${esc(leaf(p))}</div><div class="path">${esc(state.destinations[p]||join(state.project_destination||'…',leaf(p)))}</div></div><button data-action="exact-destination" data-index="${i}">Change</button></div>`).join('')}</div>`;actions=stepActions()}
  if(state.page===2){content=heading('Select data and temp.','Choose the tool data to move. Existing software can stay installed on the main drive.')+`<div class="list check-list">${state.items.length?state.items.map((item,i)=>`<label class="row"><input type="checkbox" data-item="${i}" ${state.selected.has(i)?'checked':''}><div class="row-main"><div class="row-title">${esc(item.label)}</div><div class="path">${esc(item.source)}</div></div></label>`).join(''):`<div class="empty"><strong>No known tool folders found</strong><p>Add a custom data or temp folder below.</p></div>`}</div><div class="toolbar">${button('Add data folder','add-data')}${button('Add custom temp','add-temp')}${button(icon('search')+'Find temp folders','scan-temp','quiet')}</div><h2>Future temporary files</h2><div class="temp-fields">`+field('tools_temp','Tool & build temp',state.tools_temp)+field('claude_temp','Claude temp',state.claude_temp)+'</div>';actions=stepActions()}
 if(state.page===3){content=heading('Review migration.','Check each destination. Your original files will be retained on the old drive.')+check('apps_closed','I have closed the apps and terminals using these folders.','The tool checks for running Codex and Claude processes before copying.',state.apps_closed)+`<div class="list review-list">${routes()}</div>${futureLocations()}`+check('verify_contents','Verify contents during transfer','Slower. Cleanup always rechecks every file’s contents before deleting originals.',state.verify_contents);actions=stepActions('Start migration')}
 }else if(state.view==='search'){content=heading('Choose matching folders.',state.search?.limited?'The scan reached its limit. Choose a smaller folder to find more.':'Only selected folders will be added.')+`<div class="list check-list">${(state.search?.paths||[]).map((p,i)=>`<label class="row"><input type="checkbox" data-hit="${i}"><div class="row-main"><div class="row-title">${esc(leaf(p))}</div><div class="path">${esc(p)}</div></div></label>`).join('')||'<div class="empty"><strong>No matching folders found</strong><p>Choose a folder manually or scan a smaller location.</p></div>'}</div>`;actions=`${button('Back','search-back')}<div class="right">${button('Add selected','add-hits','primary',true)}</div>`}
 else if(state.view==='progress'){let cleaning=state.snapshot?.operation==='cleanup';content=heading(cleaning?'Removing old copies.':'Moving your storage.',cleaning?'Originals are rechecked before any deletion. Completed deletions cannot be undone.':'Your original files stay on the old drive.')+`<div class="progress-area"><div class="progress-heading"><strong id="progress-title">Checking apps and folders</strong><span id="progress-percent">0%</span></div><div class="progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" aria-label="Migration progress"><div class="progress-fill"></div></div><div class="progress-meta"><span id="progress-count">Preparing…</span><span id="elapsed">Elapsed 00:00</span></div><p class="live-detail" id="detail"></p></div><div class="task-list" id="task-list"></div>`;actions=`${button('Stop safely','stop')}<div class="right">${button('Open details','record','quiet')}</div>`}
 else if(state.view==='complete'){let cleaned=state.session?.status==='cleaned';content=`<div class="success-heading">${icon('check')}<h1>${cleaned?'Old copies removed.':'Your storage has moved.'}</h1></div><p class="intro" style="margin-top:16px">${cleaned?'Your projects and selected tool data are at their new locations.':'Original copies are retained. Open your projects and check the new setup before choosing cleanup.'}</p><div class="list">${(state.session?.roots||[]).map((r,i)=>`<div class="row">${icon('folder','folder')}<div class="row-main"><div class="row-title">${esc(leaf(r.destination))}</div><div class="path">${esc(r.destination)}</div></div><button data-action="open-destination" data-index="${i}">Open</button></div>`).join('')}</div><p class="small" style="margin-top:20px">Reopen apps and terminal tabs with the new launchers to use the chosen storage settings.</p><div class="toolbar">${button('Open new projects','open-projects')}${cleaned?'':button('View original copies','backups')}${cleaned?'':button('Remove old copies…','cleanup','quiet')}</div>`;actions=`${button('Migration record','record','quiet')}<div class="right">${button('Done','close','primary')}</div>`}
 else if(state.view==='backups'||state.view==='cleanup'){let deleting=state.view==='cleanup';content=heading(deleting?'Permanently remove old copies.':'Your originals are here.',deleting?'Every old project, profile, cache and temp copy listed below will be deleted. Your new copies stay.':'Keep these backup folders, remove them manually, or choose the optional cleanup.')+`<div class="list backup-list">${(state.session?.backups||[]).map((p,i)=>`<div class="row"><div class="row-main"><div class="path">${esc(p)}</div></div>${deleting?'':`<button data-action="open-backup" data-index="${i}">Open</button>`}</div>`).join('')}</div>`;
  if(deleting){content+=`<div class="notice danger-notice">${icon('warning')}<div><strong>No undo. No Recycle Bin.</strong>These originals will be unrecoverable from the old drive. Keep a separate manual backup.</div></div>`+check('tested','I have opened and checked my projects at the new location.')+`<label for="phrase" class="small">Type this exact phrase to confirm:</label><div class="phrase">${esc(state.snapshot?.cleanup_phrase||'I UNDERSTAND MY OLD PROJECTS WILL BE DELETED AND UNRECOVERABLE')}</div><input type="text" id="phrase" autocomplete="off" spellcheck="false" placeholder="Enter the confirmation phrase">`;actions=`${button('Keep originals','complete')}<div class="right">${button('Delete old copies permanently','delete','danger',true)}</div>`}else{actions=`${button('Back','complete')}<div class="right">${button('Remove old copies…','cleanup','quiet')}</div>`}}
 else if(state.view==='failed'){content=heading('Operation stopped.','Your migration record is retained so you can resume.')+`<div class="notice danger-notice">${icon('warning')}<div>${esc(state.snapshot?.error||'An operation failed. Open the details below.')}</div></div><p class="small">${state.snapshot?.operation==='cleanup'?'Cleanup may have already removed some original files. Completed deletions cannot be undone.':'Original copies are retained. Fix the reported problem, close apps using these folders, and retry.'}</p>`;actions=`${button('Open error details','record')}<div class="right">${button(state.snapshot?.operation==='cleanup'?'Review cleanup':'Retry migration','retry','primary')}</div>`}
 $('#content').innerHTML=content;$('#content').classList.remove('page-enter');void $('#content').offsetWidth;$('#content').classList.add('page-enter');$('#actions').innerHTML=actions;$('#content').scrollTop=0;updateButtons();
 if(state.view==='setup'&&state.page===1){loadDrives();space()}
 if(state.view==='progress')progress();
 let target=$(focus)||$('h1');if(target){if(target.tagName==='H1')target.tabIndex=-1;target.focus({preventScroll:true})}
}
function stepActions(last='Continue'){return `${button('Back','back')}<div class="right">${button(last+icon('arrow'),'next','primary',state.page===1?!state.storage:state.page===3?!state.apps_closed:false)}</div>`}
function routes(){return(state.session?.roots||[]).map(r=>`<div class="row"><div class="row-main route"><div><div class="route-label">Current location</div><div class="path">${esc(r.source)}</div></div>${icon('arrow')}<div><div class="route-label">New location</div><div class="path">${esc(r.destination)}</div></div></div></div>`).join('')}
function futureLocations(){let env=state.session?.runtime||{};return `<div class="future-locations"><div><span class="small">Future tool & build temp</span><div class="path">${esc(env.TEMP||state.tools_temp)}</div></div><div><span class="small">Future Claude temp</span><div class="path">${esc(env.CLAUDE_CODE_TMPDIR||state.claude_temp)}</div></div></div>`}
function resolveDefaults(){if(!state.storage)return;let old=state.default_storage;for(let [key,parts] of [['project_destination',['Projects']],['tools_temp',['Temp','tools']],['claude_temp',['Temp','claude']]]){if(!state[key]||(old&&state[key]===join(old,...parts)))state[key]=join(state.storage,...parts)}state.default_storage=state.storage}
function saveFields(){for(let key of ['storage','project_destination','tools_temp','claude_temp'])if($('#'+key))state[key]=$('#'+key).value.trim();resolveDefaults();if($('#verify_contents'))state.verify_contents=$('#verify_contents').checked;if($('#apps_closed'))state.apps_closed=$('#apps_closed').checked}
function updateButtons(){let next=$('[data-action=next]');if(next)next.disabled=!state.ready||state.pending||(state.page===0&&!state.projects.length)||(state.page===1&&!state.storage)||(state.page===3&&!state.apps_closed);let del=$('[data-action=delete]');if(del)del.disabled=!cleanupAllowed($('#phrase')?.value,$('#tested')?.checked);let hits=$('[data-action=add-hits]');if(hits)hits.disabled=!$('[data-hit]:checked')}
function cleanupAllowed(phrase,tested){return tested===true&&phrase==='I UNDERSTAND MY OLD PROJECTS WILL BE DELETED AND UNRECOVERABLE'}
async function loadDrives(){try{let drives=await call('drives');if($('#drives'))$('#drives').innerHTML=drives.map(d=>`<button data-action="drive" data-path="${esc(d.path)}">${icon('drive')}<strong>${esc(d.path.slice(0,2))}</strong><span>${size(d.free)} free</span></button>`).join('')}catch{}}
async function space(){if(!state.storage||!$('#space'))return;try{let free=await call('available_space',state.storage);if($('#space'))$('#space').textContent=size(free)+' available'}catch{if($('#space'))$('#space').textContent='Storage unavailable'}}
function setStorage(path){state.storage=path;resolveDefaults();state.destinations={}}
async function enterData(){if(!state.items.length){state.items=await call('detected_data');let used=new Set();state.items.forEach((i,n)=>{if(!used.has(i.slot)&&i.source.toLowerCase()!==join(state.storage,...i.slot.split('/')).toLowerCase()){state.selected.add(n);used.add(i.slot)}})}}
async function prepareReview(keepAppsClosed=false){saveFields();let selection=payload(),key=JSON.stringify(selection);if(!keepAppsClosed&&state.reviewKey&&state.reviewKey!==key)state.apps_closed=false;state.session=await call('review',selection);state.reviewKey=key}
async function goToStep(page){saveFields();if(page===3)await prepareReview();if(page===2)await enterData();state.page=page;state.visited=Math.max(state.visited,page);render()}
async function next(){saveFields();if(state.page===0&&!state.projects.length)throw Error('Choose at least one project folder.');if(state.page===1&&!state.storage)throw Error('Choose a storage folder.');if(state.page===3){if(state.reviewKey!==JSON.stringify(payload())){await prepareReview();render();throw Error('The setup changed. Check the updated paths before starting.')}await call('start_migration',state.apps_closed);state.view='progress';state.snapshot={operation:'migration'};render();return}await goToStep(state.page+1)}
function payload(){return{projects:state.projects,storage:state.storage,project_destination:state.project_destination,destinations:state.destinations,tools_temp:state.tools_temp,claude_temp:state.claude_temp,verify_contents:state.verify_contents,items:state.items.filter((_,n)=>state.selected.has(n))}}
async function addFolder(kind){let p=await call('choose_folder',kind==='project'?'Choose a project folder':'Choose a dedicated data folder','');if(!p)return;if(kind==='project'){if(!state.projects.includes(p))state.projects.push(p)}else addData(p,kind);render('[data-action="add-'+kind+'"]')}
function addData(p,kind){let existing=state.items.findIndex(i=>i.source===p);if(existing>=0){state.selected.add(existing);return}state.items.push({label:kind==='temp'?'Custom temp':'Custom data',source:p,category:kind==='temp'?'temp':'custom',slot:(kind==='temp'?'Temp/Imported/':'Data/')+leaf(p)});state.selected.add(state.items.length-1)}
async function search(category,scan){saveFields();state.searchCategory=category;if(scan){let folder=await call('choose_folder','Choose where to look','');if(!folder)return;await call('scan',folder)}else await call('find_projects');state.waitingSearch=true;$('#activity').hidden=false;$('#connection').textContent='Finding folders…';for(let b of document.querySelectorAll('#actions button,main button'))b.disabled=true}
async function restore(recent){let s=await call('restore',recent);if(!s)return;state.session=s;state.view=['complete','cleaned'].includes(s.status)?'complete':'failed';state.snapshot={error:'Saved migration is ready to resume.',operation:'migration',session:s};render()}
const handlers={
 'add-project':()=>addFolder('project'),'add-data':()=>addFolder('data'),'add-temp':()=>addFolder('temp'),
 'next':next,'back':async()=>{saveFields();state.page--;render()},'find-projects':()=>search('project',false),'scan-projects':()=>search('project',true),'scan-temp':()=>search('temp',true),
 'restore':()=>restore(false),'recent':()=>restore(true),'record':()=>call('open_location','record'),'open-projects':()=>call('open_location','projects'),
 'stop':async()=>{await call('stop');let b=$('[data-action=stop]');if(b){b.disabled=true;b.textContent='Stopping safely…'}},
 'complete':async()=>{state.view='complete';render()},'backups':async()=>{state.view='backups';render()},'cleanup':async()=>{state.view='cleanup';render()},
 'delete':async()=>{let phrase=$('#phrase').value,tested=$('#tested').checked;if(!cleanupAllowed(phrase,tested))throw Error('Type the exact phrase and confirm you checked the new projects.');await call('start_cleanup',phrase,tested);state.snapshot={operation:'cleanup'};state.view='progress';render()},
 'retry':async()=>{if(state.snapshot?.operation==='cleanup'){state.view='cleanup';render()}else{await call('start_migration',true);state.view='progress';state.snapshot={operation:'migration'};render()}},
 'close':()=>call('close'),'search-back':async()=>{state.view='setup';render()},
 'add-hits':async()=>{for(let el of document.querySelectorAll('[data-hit]:checked')){let p=state.search.paths[+el.dataset.hit];if(state.searchCategory==='project'){if(!state.projects.includes(p))state.projects.push(p)}else addData(p,'temp')}state.view='setup';render()}
};
document.addEventListener('click',e=>{let step=e.target.closest('[data-step]');if(step&&!step.disabled){act(()=>goToStep(+step.dataset.step));return}let b=e.target.closest('[data-action]');if(!b||b.disabled)return;act(async()=>{let action=b.dataset.action,index=+b.dataset.index;if(action==='remove-project'){state.projects.splice(index,1);render(state.projects.length?'[data-action="remove-project"][data-index="'+Math.min(index,state.projects.length-1)+'"]':'[data-action="add-project"]')}else if(action==='exact-destination'){let p=state.projects[index],dest=await call('choose_folder','Choose exact destination',state.project_destination);if(dest){state.destinations[p]=dest;render('[data-action="exact-destination"][data-index="'+index+'"]')}}else if(action.startsWith('pick-')){saveFields();let key=action.slice(5),p=await call('choose_folder','Choose '+key.replaceAll('_',' '),state[key]);if(p){if(key==='storage')setStorage(p);else state[key]=p;render('#'+key)}}else if(action==='drive'){setStorage(join(b.dataset.path,'AI'));render('#storage')}else if(action==='open-destination'||action==='open-backup'){await call('open_location',action==='open-backup'?'backup':'destination',index)}else if(handlers[action])await handlers[action]()})});
document.addEventListener('input',e=>{if(e.target.matches('input[type=text]')){saveFields();if(e.target.id==='storage')for(let key of ['project_destination','tools_temp','claude_temp'])if($('#'+key))$('#'+key).value=state[key];if(['storage','project_destination'].includes(e.target.id))document.querySelectorAll('#content .list .row .path').forEach((el,i)=>{let p=state.projects[i];el.textContent=state.destinations[p]||join(state.project_destination,leaf(p))});updateButtons()}});
document.addEventListener('change',e=>{let el=e.target;if(el.dataset.item!==undefined){let i=+el.dataset.item;if(el.checked){for(let j of state.selected)if(state.items[j].slot===state.items[i].slot)state.selected.delete(j);state.selected.add(i)}else state.selected.delete(i);for(let box of document.querySelectorAll('[data-item]'))box.checked=state.selected.has(+box.dataset.item)}saveFields();updateButtons();if(el.id==='storage')space();if(el.id==='verify_contents')act(async()=>{await prepareReview(true);render('#verify_contents')})});
function progress(){let s=state.snapshot||{},p=s.progress||{},pct=Math.max(0,Math.min(100,p.percent||0));if(!$('#progress-percent'))return;$('#progress-percent').textContent=Math.round(pct)+'%';$('.progress-fill').style.width=pct+'%';$('.progress-track').setAttribute('aria-valuenow',pct);$('#progress-title').textContent=s.operation==='cleanup'?(pct<40?'Rechecking file contents':'Removing confirmed originals'):(pct<60?'Copying and checking files':pct<90?'Switching storage paths':pct<100?'Configuring apps and launchers':'Complete');$('#detail').textContent=p.detail||'Checking apps and folders…';$('#progress-count').textContent=p.phase==='native-copy'&&p.transfer_bytes!==undefined?size(p.transfer_bytes)+' written by Windows copy':p.total!==undefined?`${(p.done||0).toLocaleString()} / ${p.total.toLocaleString()} entries`:`${(p.done||0).toLocaleString()} entries checked`;let seconds=s.elapsed||0;$('#elapsed').textContent='Elapsed '+String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');let tasks=s.operation==='cleanup'?['Recheck old and new contents','Remove confirmed original copies']:['Copy selected folders','Switch paths to the new drive','Update app settings and launchers'];$('#task-list').innerHTML=tasks.map((name,i)=>{let limits=s.operation==='cleanup'?[40,100]:[60,90,100],start=i?limits[i-1]:0,done=pct>=limits[i];return`<div class="task-item ${done?'done':pct>=start?'active':''}">${icon(done?'check':'folder')}<span>${name}</span></div>`}).join('');if(s.stopping){let b=$('[data-action=stop]');b.disabled=true;b.textContent='Stopping safely…'}}
async function poll(){if(!api||polling)return;polling=true;try{let snap=await call('snapshot');state.snapshot=snap;if(snap.session)state.session=snap.session;if(snap.busy&&snap.operation==='search'){}else if(!snap.busy&&state.waitingSearch&&snap.operation==='search'){state.waitingSearch=false;if(snap.error){render();error(snap.error)}else{state.search={paths:snap.result?.[state.searchCategory==='project'?'projects':'temps']||[],limited:snap.result?.limited};state.view='search';render()}$('#connection').textContent='';$('#activity').hidden=true}else if(state.view==='progress'){if(!snap.busy&&snap.operation){state.view=snap.error?'failed':'complete';render()}else progress()}}catch(e){error('Desktop connection interrupted. Reopen the app to resume your saved setup.')}finally{polling=false}}
window.__uiSmoke=()=>{if(!state.ready)return{ready:false};let projects=$('h1')?.textContent==='Choose projects.',oldTheme=$('#theme').value;theme('dark');let dark=document.documentElement.dataset.theme==='dark';theme('light');let light=document.documentElement.dataset.theme==='light';theme(oldTheme);state.view='cleanup';render();let first=$('[data-action=delete]').disabled;$('#tested').checked=true;$('#phrase').value='wrong';updateButtons();let wrong=$('[data-action=delete]').disabled;$('#phrase').value='I UNDERSTAND MY OLD PROJECTS WILL BE DELETED AND UNRECOVERABLE';updateButtons();let accepted=!$('[data-action=delete]').disabled;state.view='setup';render();return{ready:true,projects,theme_switch:dark&&light&&$('#theme').options.length===3,cleanup_gate:first&&wrong&&accepted}};
window.addEventListener('pywebviewready',async()=>{api=window.pywebview.api;state.ready=true;render();await poll();setInterval(poll,300)});
render();
